#!/usr/bin/env python3
"""
promote_custom_job.py — Tailor CV for a custom URL-sourced job, save to custom_jobs.db.

Usage: promote_custom_job.py <url> --title <title> --company <company>
           --key <key> --db-path <path> [--jd-json <json_str>]

The JD is already extracted (by job_reader.py via the parse-url endpoint).
This script skips the read step and goes straight to CV tailoring.
"""

from __future__ import annotations

import atexit
import hashlib
import json
import os
import sqlite3
import subprocess
import sys
from datetime import datetime
from pathlib import Path

FORGE_HOME = Path(os.environ.get("FORGE_SYSTEM_DIR") or os.path.expanduser("~/job-hunting/job-hunting-system"))
HERMES_HOME = Path(os.environ.get("HERMES_HOME") or os.path.expanduser("~/.hermes"))
VENV_PYTHON = HERMES_HOME / "hermes-agent" / "venv" / "bin" / "python3"
PIPELINE_DIR = FORGE_HOME / "pipeline"
FLAG_DIR = FORGE_HOME / "pipeline" / ".custom_promoting"


def _get_db(path: Path) -> sqlite3.Connection:
    conn = sqlite3.connect(str(path))
    conn.row_factory = sqlite3.Row
    conn.execute("PRAGMA journal_mode=WAL")
    return conn


def run_cmd(cmd: list, label: str, timeout: int = 180) -> str:
    r = subprocess.run(
        cmd, capture_output=True, text=True, timeout=timeout,
        env={**os.environ, "FORGE_SYSTEM_DIR": str(FORGE_HOME), "HERMES_HOME": str(HERMES_HOME)},
    )
    if r.returncode != 0:
        raise RuntimeError(f"{label} failed: {r.stderr[:300]}")
    return r.stdout


def main():
    import argparse
    parser = argparse.ArgumentParser(description="Tailor CV for a custom job and save to custom_jobs.db")
    parser.add_argument("url", help="Job listing URL")
    parser.add_argument("--title", default="", help="Job title")
    parser.add_argument("--company", default="", help="Company name")
    parser.add_argument("--key", required=True, help="Job key (generated by the dashboard)")
    parser.add_argument("--db-path", required=True, help="Path to custom_jobs.db")
    parser.add_argument("--jd-json", dest="jd_json", default="",
                        help="Full JD JSON string from job_reader (already extracted)")
    args = parser.parse_args()

    db_path = Path(args.db_path)

    # Register flag cleanup so it always runs on exit
    flag_key = hashlib.md5(f"custom:{args.url}".encode()).hexdigest()
    flag_file = FLAG_DIR / f"{flag_key}.flag"

    def cleanup_flag():
        try:
            flag_file.unlink(missing_ok=True)
        except Exception:
            pass

    atexit.register(cleanup_flag)

    try:
        # Build jd_json to pass to cv_adapter
        jd_json = args.jd_json
        if not jd_json:
            jd_data = {
                "full_job_title": args.title,
                "company_name": args.company,
            }
            jd_json = json.dumps({"extracted": jd_data})

        # Tailor CV
        print("Tailoring CV...", file=sys.stderr)
        base_cv_path = FORGE_HOME / "cv" / "base_cv.json"
        cv_output_dir = FORGE_HOME / "agents" / "cv-adapter" / "outputs"
        cv_output_dir.mkdir(parents=True, exist_ok=True)

        ts = datetime.now().strftime("%Y%m%d_%H%M%S")
        safe_name = f"{args.company}_{args.title}".replace(" ", "_").replace("/", "_")[:60]
        cv_out = str(cv_output_dir / f"custom_{safe_name}_{ts}.json")

        adapter_cmd = [
            str(VENV_PYTHON), str(PIPELINE_DIR / "cv_adapter.py"),
            jd_json, str(base_cv_path), cv_out,
        ]
        adapter_out = run_cmd(adapter_cmd, "cv_adapter", timeout=300)
        adapter_result = json.loads(adapter_out)
        cv_path = adapter_result.get("path", cv_out)
        print(f"  → saved: {cv_path}", file=sys.stderr)

        # Update custom_jobs.db
        conn = _get_db(db_path)
        conn.execute(
            "UPDATE custom_jobs SET status='tailored', cv_path=? WHERE key=?",
            (cv_path, args.key),
        )
        conn.commit()
        conn.close()

        print(json.dumps({"status": "promoted", "key": args.key, "cv_path": cv_path}))

    except Exception as e:
        print(f"FAILED: {e}", file=sys.stderr)
        # Mark as failed in DB so UI can detect
        try:
            conn = _get_db(db_path)
            conn.execute(
                "UPDATE custom_jobs SET status='failed' WHERE key=? AND status='seen'",
                (args.key,),
            )
            conn.commit()
            conn.close()
        except Exception:
            pass
        sys.exit(1)


if __name__ == "__main__":
    main()
